name: hackfest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/icons/
